[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''local t = create_UIBox_generic_options({ contents = {'''
position = "before"
payload = '''local colours = UIBox_button{ label = {"Màu Lá Bài"}, button = "card_colours", minw = 5}'''
match_indent = true

# Currently not in use, but future use is highly expected