[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Alternative patch for when SMODS is not installed
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''['zh_TW'] = {font = 3, label = "繁體中文", key = 'zh_TW', beta = nil, button = "意見回饋", warning = {'這個語言目前尚為Beta版本。請幫助我們改善翻譯品質，','點擊”意見回饋” 來提供你的意見。', "再按一下即可確認"}},'''
position = "after"
payload = '''['vi'] = {font = 1, label = "Tiếng Việt", key = 'vi', beta = true, button = "Phản Hồi Ngôn Ngữ (vô dụng)", warning = {"Đây là bản dịch cá nhân và được chèn vào game thông qua Lovely.", "Nếu có thắc mắc, vui lòng liên hệ chủ bản dịch", "dưới tên theambushingbush trong máy chủ Balatro chính thức."}},'''
match_indent = true

[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = "VERSION = VERSION..'-FULL'"
position = "after"
payload = "VERSIONVN = VERSION..'-VietnameseBalatro v1.4.0 by HuyTheKiller'"
match_indent = true

[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = '''self.VERSION = VERSION'''
position = "after"
payload = '''self.VERSIONVN = VERSIONVN'''
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "{n=G.UIT.T, config={text = G.VERSION, scale = 0.3, colour = G.C.UI.TEXT_LIGHT}}"
position = "at"
payload = '''{n=G.UIT.T, config={text = SMODS and G.VERSION or G.VERSIONVN, scale = 0.3, colour = G.C.UI.TEXT_LIGHT}}'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''local t = create_UIBox_generic_options({back_func = 'options',contents = {create_tabs('''
position = "before"
payload = '''
if not SMODS then
  tabs[#tabs+1] = {
    label = "VNBalatro",
    tab_definition_function = VNBalatro.config_tab
  }
end
'''
match_indent = true